/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : PE_LDD.h
**     Project     : Ping Pong Leon
**     Processor   : MKL46Z256VMC4
**     Version     : Component 01.002, Driver 01.04, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-07-05, 05:06, # CodeGen: 96
**     Abstract    :
**
**     Settings    :
**
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file PE_LDD.h                                                  
** @version 01.04
** @brief
**
*/         
/*!
**  @addtogroup PE_LDD_module PE_LDD module documentation
**  @{
*/         
#ifndef __PE_LDD_H
#define __PE_LDD_H

/* MODULE PE_LDD. */

#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "Sonido.h"
#include "BitIoLdd1.h"
#include "c1.h"
#include "BitIoLdd2.h"
#include "c2.h"
#include "BitIoLdd3.h"
#include "c3.h"
#include "BitIoLdd4.h"
#include "c4.h"
#include "BitIoLdd5.h"
#include "c5.h"
#include "BitIoLdd6.h"
#include "c6.h"
#include "BitIoLdd7.h"
#include "c7.h"
#include "BitIoLdd8.h"
#include "c8.h"
#include "BitIoLdd9.h"
#include "f1.h"
#include "BitIoLdd10.h"
#include "f2.h"
#include "BitIoLdd11.h"
#include "f3.h"
#include "BitIoLdd12.h"
#include "f4.h"
#include "BitIoLdd13.h"
#include "f5.h"
#include "BitIoLdd14.h"
#include "f6.h"
#include "BitIoLdd15.h"
#include "f7.h"
#include "BitIoLdd16.h"
#include "f8.h"
#include "BitIoLdd17.h"
#include "c9.h"
#include "BitIoLdd20.h"
#include "c10.h"
#include "BitIoLdd21.h"
#include "c11.h"
#include "BitIoLdd22.h"
#include "c12.h"
#include "BitIoLdd23.h"
#include "c13.h"
#include "BitIoLdd24.h"
#include "c14.h"
#include "BitIoLdd25.h"
#include "c15.h"
#include "BitIoLdd26.h"
#include "c16.h"
#include "BitIoLdd27.h"
#include "Matriz.h"
#include "Procesamiento.h"
#include "UP1.h"
#include "ExtIntLdd1.h"
#include "PTA.h"
#include "UP2.h"
#include "ExtIntLdd3.h"
#include "DOWN1.h"
#include "ExtIntLdd4.h"
#include "DOWN2.h"
#include "ExtIntLdd2.h"
#include "Vida1_J1.h"
#include "BitIoLdd18.h"
#include "Vida2_J1.h"
#include "BitIoLdd19.h"
#include "Vida3_J1.h"
#include "BitIoLdd28.h"
#include "Vida1_J2.h"
#include "BitIoLdd30.h"
#include "Vida2_J2.h"
#include "BitIoLdd29.h"
#include "Vida3_J2.h"
#include "BitIoLdd31.h"


/*
** ===================================================================
** Function prototypes
** ===================================================================
*/

/*
** ===================================================================
**     Method      :  Microcontrolador_PE_FillMemory (component MKL46Z256MC4)
*/
/*!
**     @brief
**         Fills a memory area block by a specified value.
**     @param
**       SourceAddressPtr - Source address pointer.
**     @param
**       c - A value used to fill a memory block.
**     @param
**       len - Length of a memory block to fill.
*/
/* ===================================================================*/
void PE_FillMemory(register void* SourceAddressPtr, register uint8_t c, register uint32_t len);

/*
** ===================================================================
**     Method      :  Microcontrolador_PE_PeripheralUsed (component MKL46Z256MC4)
*/
/*!
**     @brief
**         Returns information whether a peripheral is allocated by PEx 
**         or not.
**     @param
**       PrphBaseAddress - Base address of a peripheral.
**     @return
**       TRUE if a peripheral is used by PEx or FALSE if it isn't used.
*/
/* ===================================================================*/
bool PE_PeripheralUsed(uint32_t PrphBaseAddress);

/*
** ===================================================================
**     Method      :  Microcontrolador_LDD_SetClockConfiguration (component MKL46Z256MC4)
*/
/*!
**     @brief
**         Changes the clock configuration of all LDD components in a 
**         project.
**     @param
**       ClockConfiguration - New CPU clock configuration changed by CPU SetClockConfiguration method.
*/
/* ===================================================================*/
void LDD_SetClockConfiguration(LDD_TClockConfiguration ClockConfiguration);

/* END PE_LDD. */


#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
